services:
  schedule-arranger:
    build:
      context: .
    container_name: schedule-arranger-service
    ports:
      - "8000:8000"
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    volumes:
      - ./uploads:/var/www/html/uploads
    environment:
      - DB_HOST=db
      - DB_NAME=library
      - DB_USER=admin
      - DB_PASS=admin123
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: schedule-arranger-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: library
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3307:3306"
    volumes:
      - schedule-arranger-mysql:/var/lib/mysql

volumes:
  schedule-arranger-mysql:
    driver: local
  schedule-arranger-uploads:
    driver: local
